
server:
  port: 9094

spring:
  data:
    mongodb:
      database: musaladrone
      host: localhost
      port: 27017
      auto-index-creation: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher